export const PRODUCT_LIST = [
  {
    id: 101,
    name: "iPhone 17 Pro Max",
    category: "iPhone",
    badge: "New",
    image:
      "https://cdn.tgdd.vn/Products/Images/42/342680/s16/iphone-17-pro-max-cam-thumb-650x650.png",
    price: 34990000,
    oldPrice: 37990000,
    rating: 4.9,
    reviews: 224,
    description:
      "A19 Pro, titanium frame, all-day battery, and advanced camera system.",
    variants: ["256GB", "512GB", "1TB", "2TB"],
    colors: [
      { label: "Cam Vũ Trụ", hex: "#c47b58" },
      { label: "Sa Mạc Titan", hex: "#c8b89a" },
      { label: "Đen Titan", hex: "#3d3632" },
      { label: "Trắng Titan", hex: "#f0ede8" },
    ],
  },
  {
    id: 102,
    name: "iPhone 17",
    category: "iPhone",
    badge: "Popular",
    image:
      "https://cdn.tgdd.vn/Products/Images/42/342679/s16/iphone-17-den-thumb-650x650.png",
    price: 25990000,
    oldPrice: 27990000,
    rating: 4.8,
    reviews: 193,
    description:
      "Fast, light, and reliable with a brighter display for daily use.",
    variants: ["128GB", "256GB", "512GB"],
    colors: [
      { label: "Đen", hex: "#1d1d1f" },
      { label: "Trắng", hex: "#f5f5f7" },
      { label: "Xanh Lam Khói", hex: "#6a8fa0" },
      { label: "Xanh Lá Xô Thơm", hex: "#7a9977" },
    ],
  },
  {
    id: 103,
    name: "iPad Pro M5 13-inch",
    category: "iPad",
    badge: "New",
    image:
      "https://cdn.tgdd.vn/Products/Images/522/358099/s16/ipad-pro-m5-wifi-13-inch-black-thumbtz-650x650.png",
    price: 32990000,
    oldPrice: null,
    rating: 4.9,
    reviews: 89,
    description:
      "Ultra thin design and M5 performance for creators and power users.",
    variants: ["256GB", "512GB", "1TB", "2TB"],
    colors: [
      { label: "Đen", hex: "#1d1d1f" },
      { label: "Trắng Bạc", hex: "#e8e8ed" },
    ],
  },
  {
    id: 104,
    name: "iPad Air 11-inch",
    category: "iPad",
    badge: null,
    image:
      "https://cdn.tgdd.vn/Products/Images/522/328576/s16/ipad-air-11-inch-m3-wifi-blue-thumb-650x650.png",
    price: 17990000,
    oldPrice: 19990000,
    rating: 4.7,
    reviews: 141,
    description:
      "Portable iPad with strong performance and smooth multitasking.",
    variants: ["128GB", "256GB", "512GB"],
    colors: [
      { label: "Xanh Dương", hex: "#4a90d9" },
      { label: "Tím", hex: "#9b84ad" },
      { label: "Ánh Sao", hex: "#e8e0d0" },
      { label: "Xám", hex: "#8e8e93" },
    ],
  },
  {
    id: 105,
    name: "MacBook Pro 14 M5 Pro",
    category: "Mac",
    badge: "Pro",
    image:
      "https://cdn.tgdd.vn/Products/Images/44/363488/s16/macbook-pro-14-inch-m5-pro-24gb-1tb-den-thumb-650x650.png",
    price: 56990000,
    oldPrice: 59990000,
    rating: 4.9,
    reviews: 56,
    description:
      "Desktop class power in a compact laptop for engineering workloads.",
    variants: ["512GB", "1TB", "2TB"],
    colors: [
      { label: "Đen Thiên Hà", hex: "#2d2926" },
      { label: "Bạc", hex: "#c7c7cc" },
    ],
  },
  {
    id: 106,
    name: "MacBook Air 15 M4",
    category: "Mac",
    badge: null,
    image:
      "https://cdn.tgdd.vn/Products/Images/44/334852/s16/macbook-air-15-inch-m4-midnight-thumb-650x650.png",
    price: 32990000,
    oldPrice: 34990000,
    rating: 4.8,
    reviews: 128,
    description:
      "Thin and silent laptop with strong battery for work and travel.",
    variants: ["256GB", "512GB", "1TB"],
    colors: [
      { label: "Đêm Trung Thu", hex: "#2b3048" },
      { label: "Ánh Sao", hex: "#e8dfd0" },
      { label: "Vàng Thủy Tinh", hex: "#d4c9a8" },
      { label: "Bầu Trời", hex: "#b0c4d8" },
    ],
  },
  {
    id: 107,
    name: "Apple Watch Series 11",
    category: "Watch",
    badge: "Hot",
    image:
      "https://cdn.tgdd.vn/Products/Images/7077/344750/s16/apple-watch-series-11-42mm-vien-nhom-day-the-thao-vang-hong-thumb-650x650.png",
    price: 11990000,
    oldPrice: 12990000,
    rating: 4.8,
    reviews: 176,
    description:
      "Health insights, smarter workouts, and quick notifications on your wrist.",
    variants: ["42mm", "46mm"],
    colors: [
      { label: "Vàng Hồng", hex: "#e8b4a0" },
      { label: "Ánh Sao", hex: "#e0dbd0" },
      { label: "Đen", hex: "#1d1d1f" },
      { label: "Xanh Lam", hex: "#4a90d9" },
    ],
  },
  {
    id: 108,
    name: "Apple Watch Ultra 3",
    category: "Watch",
    badge: "New",
    image:
      "https://cdn.tgdd.vn/Products/Images/7077/344791/s16/apple-watch-ultra-3-titanium-day-ocean-xanh-duong-thumb-650x650.png",
    price: 21990000,
    oldPrice: null,
    rating: 4.9,
    reviews: 63,
    description:
      "Rugged build and long battery life for outdoor and endurance sports.",
    variants: ["49mm"],
    colors: [
      { label: "Titan Tự Nhiên", hex: "#b8a990" },
      { label: "Titan Đen", hex: "#3d3a36" },
      { label: "Titan Trắng", hex: "#e8e4df" },
    ],
  },
  {
    id: 109,
    name: "AirPods Pro 3",
    category: "Audio",
    badge: "New",
    image:
      "https://cdn.tgdd.vn/Products/Images/54/329154/s16/airpods-4-thumb-1-650x650.png",
    price: 6990000,
    oldPrice: 7490000,
    rating: 4.8,
    reviews: 284,
    description: "Adaptive noise control and spatial audio in a compact form.",
    variants: ["Lightning", "USB-C"],
    colors: [{ label: "Trắng", hex: "#f5f5f7" }],
  },
  {
    id: 110,
    name: "AirPods Max USB-C",
    category: "Audio",
    badge: null,
    image:
      "https://cdn.tgdd.vn/Products/Images/54/334358/s16/tai-nghe-chup-tai-airpods-max-usb-c-thumb-650x650.png",
    price: 13990000,
    oldPrice: 14990000,
    rating: 4.7,
    reviews: 45,
    description: "Premium over-ear audio with active noise cancellation.",
    variants: ["Midnight", "Starlight", "Blue"],
    colors: [
      { label: "Đêm Trung Thu", hex: "#2b3048" },
      { label: "Ánh Sao", hex: "#e8dfd0" },
      { label: "Xanh Dương", hex: "#4a90d9" },
      { label: "Hồng", hex: "#e8a0b4" },
      { label: "Vàng Nhạt", hex: "#d4c9a8" },
    ],
  },
  {
    id: 111,
    name: "MagSafe Silicone Case",
    category: "Accessories",
    badge: null,
    image:
      "https://cdnv2.tgdd.vn/mwg-static/topzone/Products/Images/60/342314/op-lung-magsafe-iphone-17-pro-max-pc-tpu-ava-oc-bayer-ii-thumb-638926764707918633-650x650.png",
    price: 1190000,
    oldPrice: null,
    rating: 4.6,
    reviews: 72,
    description:
      "Soft touch finish with MagSafe alignment and everyday protection.",
    variants: ["iPhone 16", "iPhone 17"],
    colors: [
      { label: "Đen", hex: "#1d1d1f" },
      { label: "Đỏ", hex: "#c0392b" },
      { label: "Xanh Dương", hex: "#4a90d9" },
    ],
  },
  {
    id: 112,
    name: "Apple 70W USB-C Adapter",
    category: "Accessories",
    badge: null,
    image:
      "https://cdn.tgdd.vn/Products/Images/9499/309907/s16/adapter-sac-apple-type-c-70w-thumb-650x650.png",
    price: 1590000,
    oldPrice: 1790000,
    rating: 4.7,
    reviews: 109,
    description: "Fast and stable charging for MacBook, iPad, and iPhone.",
    variants: ["70W"],
    colors: [{ label: "Trắng", hex: "#f5f5f7" }],
  },
];
