require("dotenv").config();
const mongoose = require("mongoose");
const Category = require("./models/Category");
const Product  = require("./models/Product");

async function main() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("✅ Connected");

  const categories = await Category.find({});
  const catMap = {};
  categories.forEach((c) => (catMap[c.name] = c._id));

  const productData = [
    {
      name: "iPhone 17 Pro",
      slug: "iphone-17-pro",
      description: "The ultimate iPhone with A19 Pro chip and stunning titanium design.",
      category: catMap["iPhone"],
      basePrice: 34990000,
      salePrice: 33990000,
      stock: 145,
      sold: 320,
      tags: ["iphone", "apple", "smartphone"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/42/342676/s16/iphone-17-pro-cam-thumb-650x650.png", publicId: "iphone-17-pro_1", isPrimary: true }],
    },
    {
      name: "iPhone 16 Pro",
      slug: "iphone-16-pro",
      description: "Pro camera system and A18 Pro chip for unprecedented performance.",
      category: catMap["iPhone"],
      basePrice: 28990000,
      salePrice: null,
      stock: 89,
      sold: 410,
      tags: ["iphone", "apple", "smartphone"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/42/329148/s16/iphone-16-pro-den-650x650.png", publicId: "iphone-16-pro_1", isPrimary: true }],
    },
    {
      name: "iPhone 15 Pro Max",
      slug: "iphone-15-pro-max",
      description: "Forged in titanium and featuring the groundbreaking A17 Pro chip.",
      category: catMap["iPhone"],
      basePrice: 29990000,
      salePrice: 28990000,
      stock: 210,
      sold: 150,
      tags: ["iphone", "apple", "smartphone"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/42/305660/s16/iphone-15-pro-max-black-1-2-650x650.png", publicId: "iphone-15-pro-max_1", isPrimary: true }],
    },
    {
      name: "iPhone 14",
      slug: "iphone-14",
      description: "Advanced camera system for better photos in any light.",
      category: catMap["iPhone"],
      basePrice: 18990000,
      salePrice: 16990000,
      stock: 50,
      sold: 280,
      tags: ["iphone", "apple", "smartphone"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/42/240259/s16/iphone-14-blue-1-2-650x650.png", publicId: "iphone-14_1", isPrimary: true }],
    },
    {
      name: "iPad Air M3 11-inch",
      slug: "ipad-air-m3-11",
      description: "Supercharged by the Apple M3 chip with an 11-inch Liquid Retina display.",
      category: catMap["iPad"],
      basePrice: 16990000,
      salePrice: 16490000,
      stock: 125,
      sold: 45,
      tags: ["ipad", "apple", "tablet"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/522/335267/s16/ipad-air-m3-11-inch-wifi-starlight-thumb-650x650.png", publicId: "ipad-air-m3-11_1", isPrimary: true }],
    },
    {
      name: "iPad Pro M5 11-inch",
      slug: "ipad-pro-m5-11",
      description: "The ultimate iPad experience with the incredibly powerful M5 chip.",
      category: catMap["iPad"],
      basePrice: 28990000,
      salePrice: 27990000,
      stock: 68,
      sold: 110,
      tags: ["ipad", "apple", "tablet", "pro"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/522/358082/s16/ipad-pro-m5-wifi-11-inch-black-thumbtz-650x650.png", publicId: "ipad-pro-m5-11_1", isPrimary: true }],
    },
    {
      name: "iPad 11 WiFi",
      slug: "ipad-11-wifi",
      description: "The completely redesigned iPad in vibrant colors.",
      category: catMap["iPad"],
      basePrice: 10990000,
      salePrice: null,
      stock: 250,
      sold: 490,
      tags: ["ipad", "apple", "tablet"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/522/335308/s16/ipad-11-wifi-yellow-thumb-650x650.png", publicId: "ipad-11-wifi_1", isPrimary: true }],
    },
    {
      name: "iPad mini 7 WiFi",
      slug: "ipad-mini-7-wifi",
      description: "Mega power in a mini size with the A17 Pro chip.",
      category: catMap["iPad"],
      basePrice: 14990000,
      salePrice: 13990000,
      stock: 180,
      sold: 65,
      tags: ["ipad", "apple", "tablet", "mini"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/522/331229/s16/ipad-mini-7-wifi-purple-thumbtz-650x650.png", publicId: "ipad-mini-7-wifi_1", isPrimary: true }],
    },
    {
      name: "MacBook Air 13-inch M4",
      slug: "macbook-air-13-m4-base",
      description: "Lean, mean, M4 machine with up to 18 hours of battery life.",
      category: catMap["Mac"],
      basePrice: 27990000,
      salePrice: 26990000,
      stock: 45,
      sold: 130,
      tags: ["macbook", "apple", "laptop"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/44/335362/s16/macbook-air-13-inch-m4-thumb-xanh-den-650x650.png", publicId: "macbook-air-13-m4-base_1", isPrimary: true }],
    },
    {
      name: "MacBook Pro 14-inch M5",
      slug: "macbook-pro-14-m5-base",
      description: "Mind-blowing performance for pros with the M5 chip.",
      category: catMap["Mac"],
      basePrice: 39990000,
      salePrice: null,
      stock: 30,
      sold: 80,
      tags: ["macbook", "apple", "laptop", "pro"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/44/358086/s16/macbook-pro-14-inch-m5-16gb-512gb-den-650x650.png", publicId: "macbook-pro-14-m5-base_1", isPrimary: true }],
    },
    {
      name: "MacBook Air 15-inch M5",
      slug: "macbook-air-15-m5-base",
      description: "Impossibly thin design with a spacious 15-inch display.",
      category: catMap["Mac"],
      basePrice: 32990000,
      salePrice: 31990000,
      stock: 105,
      sold: 55,
      tags: ["macbook", "apple", "laptop"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/44/363477/s16/macbook-air-15-inch-m5-16gb-512gb-xanh-da-troi-nhat-650x650.png", publicId: "macbook-air-15-m5-base_1", isPrimary: true }],
    },
    {
      name: "Apple Watch Series 10",
      slug: "apple-watch-series-10",
      description: "A healthy leap ahead with advanced health sensors.",
      category: catMap["Watch"],
      basePrice: 11990000,
      salePrice: 10990000,
      stock: 220,
      sold: 340,
      tags: ["watch", "apple", "smartwatch"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/7077/329708/s16/apple-watch-series-10-lte-42mm-day-vai-xanh-nhat-tb-650x650.png", publicId: "apple-watch-series-10_1", isPrimary: true }],
    },
    {
      name: "Apple Watch SE 3",
      slug: "apple-watch-se-3-base",
      description: "Heavy on features. Light on price.",
      category: catMap["Watch"],
      basePrice: 7490000,
      salePrice: null,
      stock: 190,
      sold: 450,
      tags: ["watch", "apple", "smartwatch"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/7077/344767/s16/apple-watch-se-3-40mm-vien-nhom-day-the-thao-starlight-thumb-650x650.png", publicId: "apple-watch-se-3-base_1", isPrimary: true }],
    },
    {
      name: "Apple Watch Ultra 3",
      slug: "apple-watch-ultra-3-ocean",
      description: "The most rugged and capable Apple Watch ever.",
      category: catMap["Watch"],
      basePrice: 22990000,
      salePrice: 21990000,
      stock: 45,
      sold: 120,
      tags: ["watch", "apple", "smartwatch", "ultra"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/7077/344764/s16/apple-watch-ultra-3-gps-cellular-49mm-vien-titanium-day-ocean-titan-thumb-650x650.png", publicId: "apple-watch-ultra-3-ocean_1", isPrimary: true }],
    },
    {
      name: "AirPods Pro 2",
      slug: "airpods-pro-2-base",
      description: "Richer audio, enhanced Active Noise Cancellation.",
      category: catMap["Audio"],
      basePrice: 6190000,
      salePrice: 5990000,
      stock: 300,
      sold: 480,
      tags: ["audio", "apple", "airpods"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/54/315014/s16/tai-nghe-bluetooth-airpods-pro-2nd-gen-usb-c-charge-apple-thumb-12-1-650x650.png", publicId: "airpods-pro-2-base_1", isPrimary: true }],
    },
    {
      name: "AirPods 4",
      slug: "airpods-4-base",
      description: "An entirely new way to experience audio.",
      category: catMap["Audio"],
      basePrice: 4290000,
      salePrice: null,
      stock: 150,
      sold: 210,
      tags: ["audio", "apple", "airpods"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/54/329158/s16/airpods-4-thumb-650x650.png", publicId: "airpods-4-base_1", isPrimary: true }],
    },
    {
      name: "EarPods with USB-C",
      slug: "earpods-usb-c-base",
      description: "High-quality audio and an integrated remote.",
      category: catMap["Audio"],
      basePrice: 590000,
      salePrice: 490000,
      stock: 280,
      sold: 350,
      tags: ["audio", "apple", "earpods"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/54/315072/s16/tai-nghe-co-day-apple-mtjy3-thumb-650x650.png", publicId: "earpods-usb-c-base_1", isPrimary: true }],
    },
    {
      name: "Apple 20W USB-C Power Adapter",
      slug: "apple-20w-usb-c-adapter-base",
      description: "Fast, efficient charging at home, in the office, or on the go.",
      category: catMap["Accessories"],
      basePrice: 550000,
      salePrice: 490000,
      stock: 290,
      sold: 490,
      tags: ["accessory", "apple", "charger"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/9499/230315/s16/adapter-sac-type-c-20w-cho-iphone-ipad-apple-mhje3-101021-023343-650x650.png", publicId: "apple-20w-usb-c-adapter-base_1", isPrimary: true }],
    },
    {
      name: "Apple Pencil Pro",
      slug: "apple-pencil-pro-base",
      description: "Pixel-perfect precision and industry-leading low latency.",
      category: catMap["Accessories"],
      basePrice: 3490000,
      salePrice: 3290000,
      stock: 120,
      sold: 230,
      tags: ["accessory", "apple", "pencil"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/1882/325539/s16/apple-pencil-pro-650x650.png", publicId: "apple-pencil-pro-base_1", isPrimary: true }],
    },
    {
      name: "MagSafe Silicone Case for iPhone 17 Pro Max",
      slug: "magsafe-silicone-case-iphone-17-pro-max-base",
      description: "Designed to protect your iPhone with a silky, soft-touch finish.",
      category: catMap["Accessories"],
      basePrice: 1490000,
      salePrice: null,
      stock: 160,
      sold: 80,
      tags: ["accessory", "apple", "case"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/60/345676/s16/op-lung-magsafe-iphone-17-pro-max-techwoven-apple-thumb-650x650.png", publicId: "magsafe-silicone-case-iphone-17-pro-max-base_1", isPrimary: true }],
    },
    {
      name: "Apple 70W USB-C Power Adapter",
      slug: "apple-70w-usb-c-adapter-base",
      description: "Fast, efficient charging for your MacBook Air or MacBook Pro.",
      category: catMap["Accessories"],
      basePrice: 1690000,
      salePrice: 1590000,
      stock: 85,
      sold: 110,
      tags: ["accessory", "apple", "charger"],
      isFlashSale: false,
      images: [{ url: "https://cdn.tgdd.vn/Products/Images/9499/309907/s16/adapter-sac-apple-type-c-70w-thumb-650x650.png", publicId: "apple-70w-usb-c-adapter-base_1", isPrimary: true }],
    }
  ];

  await Product.insertMany(productData);
  console.log(`✅ Đã seed ${productData.length} sản phẩm`);
  await mongoose.disconnect();
}

main().catch(console.error);
